### ISSUE TITLE
[Feature Request] Multiple binning input options

### ISSUE THREAD

**Issue by jolespin** [metagentools/GraphBin#12]
Is it possible to add a matrix of binning methods? For example in the test data you have maxbin2, metabat2, etc.  Can all of these be used at once?

**Comment by Vini2** [comment]
Dear @jolespin,

Currently, GraphBin handles only one binning result (from one tool). Multiple binning results from multiple tools cannot be provided in one run.

Thank you!

**Comment by nvpatin** [comment]
On a similar note: is it possible to use input from a binning process that used two different assemblies? MaxBin2 and others can take advantage of differential coverage across multiple assemblies to bin more accurately. I assume the answer is no, but might be a good improvement for the future. Thank you!

**Comment by Vini2** [comment]
Hi @nvpatin,

Currently, GraphBin does not make use of the coverage information from coassemblies. Thank you very much for the suggestion. We will definitely work on it.

Thank you!
