### ISSUE TITLE
Can GraphBin be used with a co-binning approach?

### ISSUE THREAD

**Issue by Laura-Alex** [metagentools/GraphBin#16]
I've used MEGAHIT to assemble samples individually, and then ran vamb in order to bin them all together.

I was wondering whether GraphBin can cope with / be used to refine this type of input. There is one binning input, so  that should be all right as long as I make sure the contig names are the same. For the contigs file, I can concatenate the individual contigs so there is one input file. But I'm confused about the assembly graph file. I guess I could concatenate all neccesary fastg files, while taking care to have only one begin and end line, and then convert to gfa...but in that case, should the fastg file include one, or multiple 'assembly name' lines? Do you have any idea?

Kind regards,

Laura

**Comment by Vini2** [comment]
Hello @Laura-Alex,

Thanks for your interest in GraphBin.

There can be cases where the same contig identifier appears in two or more samples. So you should rename the contigs in the contig file to be sample-specific. For the assembly graphs, first, you can convert the individual FASTG files to GFA and rename the contig identifiers to be sample-specific as well. Then you can concatenate the contig files separately to make one FASTA file and the graph files separately to make one GFA file. 

I guess this should work fine but I'm not sure until I test it. I will test this and get back to you ASAP.

Thanks for your question!

Best regards,
Laura

**Comment by Vini2** [comment]
Hello @Laura-Alex,

I think you can use an assembler such as Flye and do a population assembly using the contigs from all the MEGAHIT assemblies and get a non-redundant set of contigs. This sort of assembly is done in [Hecatomb](https://github.com/shandley/hecatomb) tool. Then you can run the Flye version of GraphBin on the resulting contigs and Flye assembly graph.

Hope this helps.

Best regards,
Vijini
