### ISSUE TITLE
 qusetion of score 

### ISSUE THREAD

**Issue by mant-ux** [metagentools/GraphBin#19]
[](https://github.com/Vini2/GraphBin/issues/new###)[](javascript:void(0);)[](https://github.com/Vini2/GraphBin/issues/new###)
Hello, I want to ask you how to calculate ARI in graphbin, because the number of contings marked by different bining tools is different. For example, metabat has a very high precison, but the number of contings that can be obtained is very small. How do you weigh the different number of different tools when calculating ARI? If only calculate the corresponding number of contings bined into bins , the ARI of metabat should be very high,is it?

Another question. When will metacoag be officially released? Can I quote your method in mt paper？It’s a good tools.

Thank you very much!

**Comment by Vini2** [comment]
Hello @mant-ux,

Thank you for the question. We followed the notations of binning results and the definitions from CONCOCT, d2sBin and SolidBin papers. ARI considers only the contigs being binned by the tool.

MetaCoAG has been accepted at RECOMB 2022 and will be published soon. You can cite the preprint available at bioRxiv [(https://doi.org/10.1101/2021.09.10.459728](https://doi.org/10.1101/2021.09.10.459728).

Thank you very much for your comments and interest in my tools!
