### ISSUE TITLE
link disappeared

### ISSUE THREAD

**Issue by masterhan666** [metagentools/GraphBin#38]
https://graphbin.readthedocs.io/en/latest/usage/
The link on how to convert fastg to gfa files in the above URL disappears.
I want to know how to convert fastg to gfa.
Thank you

**Comment by Vini2** [comment]
Hello @masterhan666,

Seems like the GitHub repository has been removed. I will check if there are any other implementations available to do the fastg to gfa conversion.

**Comment by Vini2** [comment]
Hello @masterhan666,

I think you can use `gfastats` ([https://github.com/vgl-hub/gfastats](https://github.com/vgl-hub/gfastats)) to convert fastg to gfa.

**Comment by Vini2** [comment]
Please reopen the issue if needed.
