### ISSUE TITLE
Please depend on 'igraph' instead of 'python-igraph' on PyPI

### ISSUE THREAD

**Issue by szhorvat** [metagentools/GraphBin#43]
Please depend on the `igraph` instead of `python-igraph` package on PyPI. See https://github.com/igraph/python-igraph/issues/699 for an explanation.

I believe this requires changes only in `requirements.txt` and `pyproject.toml` here:

https://github.com/search?q=repo%3Ametagentools%2FGraphBin%20python-igraph&type=code

Note that on conda-forge, the name stays `python-igraph`!

**Comment by Vini2** [comment]
Hi @szhorvat,

Thanks for bringing this to my attention by posting this issue. I will make the necessary updates ASAP.

**Comment by szhorvat** [comment]
Thank you @Vini2 !
